### ISSUE TITLE
website is a black screen

### ISSUE THREAD

**Issue by ac8736** [DLi7077/katsudon-client#40]
its just a black screen right now

**Comment by dli7077** [comment]
Yeah I messed up on some state variables for users that are logged out. Will look into it later today.

**Comment by dli7077** [comment]
Expecting the bug to be in app.js

**Comment by ac8736** [comment]
you pushed code that broke deployment

**Comment by dli7077** [comment]
it wAs WorKiNG oN mY mAchiNe

**Comment by dli7077** [comment]
fixed
